# 行列積
以下のような行列A、Bを考えます。
<br />
<br />
$$
% <![CDATA[
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right] %]]>
$$
<br />
NumPyで表すと次のようになります

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

### 【問題1】解答

(-1 × 0 + 2 × 0 + 3 × 2) + (-1 × 2 + 2 × 2 + 3 × 9) + (-1 × 1 + 2 × -8 + 3 × -1)

(4 × 0 + -5 × 0 + 6 × 2) + (4 × 2 + -5 × 2 + 6 × 9) + (4 × 1 + -5 × -8 + 6 × -1)

(7 × 0 + 8 × 0 + -9 × 2) + (7 × 2 + 8 × 2 + -9 × 9) + (7 × 1 + -8 × -8 + -9 × -1)



  6  29 -20

 12  52  38

-18 -51 -48

In [2]:
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題2】NumPyの関数による計算
この行列積はNumPyの**np.matmul()**や**np.dot()**、または**@**演算子
を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

[numpy.matmul — NumPy v1.16 Manual
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)

[numpy.dot — NumPy v1.16 Manual
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

### 【問題2】解答

In [3]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# np.matmul
by_np_matmul = np.matmul(a_ndarray, b_ndarray)
print(by_np_matmul)

# np.dot()
by_np_dot = np.dot(a_ndarray, b_ndarray)
print(by_np_dot)

# @演算子
by_at = a_ndarray@b_ndarray
print(by_at)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 《3種類の違い》

**np.matmul()**と**np.dot()**は3次元以上の配列で挙動が変わります。**@**演算子は**np.matmul()**と同じ働きをします。

今回のような2次元配列の行列積では**np.matmul()**や**@**演算子が公式に推奨されています。以下は**np.dot()**の説明からの引用です。

>If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

# 行列積のスクラッチ実装

`np.matmul()`や`np.dot()`、または`@`演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。



## 【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1. 行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
2. 行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる
3. 行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる
4. それらの値を全て足し合わせる

数式で表すと

$$
\sum^{2}_{k=0}a_{0,k}b_{k,0}
$$

です。

この計算を`np.matmul()`や`np.dot()`、または`@`演算子を使わずに行うコードを書いてください。

### 【問題3】解答

In [4]:
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

val = []
for i in range(a.shape[1]):
    val.append(a[:,i]*b[i,:])
sum(val)

array([  6,  52, -48])

## 【問題4】行列積を行う関数の作成

問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である 3×3 の行列Cの各要素 $c_{i,j}$は数式で表すと次のようになります。
<br /><br />
$$
c_{i,j} = \sum^{2}_{k=0}a_{i,k}b_{k,j}
$$
<br /><br />
for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス *i* や *j* を1増やすと、次の行や列に移ることができます。

![代替テキスト](https://t.gyazo.com/teams/diveintocode/129123df5242c9e768513f5e8b5ef24f.png)

In [11]:
def matrix_multiplication_scratch(a, b):
    val_list = []
    for k in range(a.shape[0]):
        for j in range(b.shape[1]):
            val = []
            for i in range(a.shape[1]):
                val.append(a[k,i]*b[i,j])
            val_list.append((sum(val)))
    return np.array(val_list).reshape(-1, b.shape[1])

print(matrix_multiplication_scratch(a, b))
print(a@b)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 行列積が定義されない組み合わせの行列
次に以下のような例を考えます。

<br />
$$
% <![CDATA[
D = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6
    \end{array}
  \right],
  E- = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4
    \end{array}
  \right] %]]>
$$


In [6]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることを`print()`を使い表示するコードを書き加えてください。

### 【問題5】解答

In [7]:
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])

def matrix_multiplication_scratch(a, b):
    if a.shape[1] != b.shape[0]:
        return '行列数エラー'
    else:
        val_list = []
        for k in range(a.shape[0]):
            for j in range(b.shape[1]):
                val = []
                for i in range(a.shape[1]):
                    val.append(a[k,i]*b[i,j])
                val_list.append((sum(val)))
        return np.array(val_list).reshape(-1, b.shape[1])


matrix_multiplication_scratch(d, e)

'行列数エラー'

## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

`np.transpose()`や.`T`アトリビュートを用いて転置し、行列積を計算してください。

[numpy.transpose — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)

[numpy.ndarray.T — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)

In [10]:
def matrix_multiplication_scratch(a, b):
    if a.shape[1] != b.shape[0]:
        return '行列数エラー'
    else:
        val_list = []
        for k in range(a.shape[0]):
            for j in range(b.shape[1]):
                val = []
                for i in range(a.shape[1]):
                    val.append(a[k,i]*b[i,j])
                val_list.append((sum(val)))
        return np.array(val_list).reshape(-1, b.shape[1])

e.T.shape
print(matrix_multiplication_scratch(d, e.T))
print(d@e.T)

[[ 46  -4]
 [-34  73]]
[[ 46  -4]
 [-34  73]]
